name: signalrapptest_iac

on:
  push:
    branches: [master]
    paths:
      - "bicep/**"
  # pull_request:
  #   branches: [master]

jobs:
  deploy:
    environment: signalrapp_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_APPRG }}

      - name: Deploy bicep
        working-directory: bicep/
        run: |
          az deployment group what-if   \
          --name apprg \
          --resource-group '${{ secrets.RG_NAME }}' \
          --template-file appservicestuff.bicep \
          --parameters ${{ secrets.APP_SETTINGS }}
