name: signalrapptest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildbackend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend/

      - name: Build backend
        run: dotnet build -c Release --no-restore
        working-directory: backend/

      - name: Test backend
        run: dotnet test -c Release --no-build --verbosity normal
        working-directory: backend/

      - name: Publish backend
        run: dotnet publish -c Release --no-build --verbosity normal -o publish/
        working-directory: backend/backend/

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: |
            backend/backend/publish

  buildfrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      # - name: Test frontend
      #   run: npm test
      #   working-directory: frontend/
      #   env:
      #     CI: true

      - name: Build frontend
        run: npm run build
        working-directory: frontend/

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: |
            frontend/build

  merge:
    runs-on: ubuntu-latest
    needs: [buildbackend, buildfrontend]
    steps:
      - uses: actions/download-artifact@v3

      - name: Create appservice package
        run: |
          mkdir backend/wwwroot && cp -r frontend/* backend/wwwroot/ && (cd backend && zip -r ../app.zip .)

      - name: Upload app artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            app.zip



  deploy:
    environment: signalrapp_test
    runs-on: ubuntu-latest
    needs: [merge]
    steps:     
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_APPRG }}
    


